import { Client } from "pg";
import { assertTestDatabase } from "./assert-test-db";

/**
 * Remove the global rows earlier runs left behind in the test database.
 *
 * Almost everything the suites create is tenant-scoped, so it disappears from
 * view with its tenant. Plans and feature flags are not: they belong to the
 * platform. Eight specs create them, none removed them, and after a few months
 * the test database held 1092 active plans.
 *
 * That is not merely untidy. The public landing page lists every active plan —
 * correctly — so the guide filmed a pricing section that was a wall of
 * "Verify Plan", "archive-plan Plan 1786315523640" and 1090 others. It is the
 * first thing a viewer sees.
 *
 * The rule is deliberately narrow: a name carrying a 13-digit millisecond
 * timestamp was generated by a machine. A real plan ("Essentiel", "Pro") never
 * matches, so this cannot quietly delete the product's own configuration.
 *
 * Plans are retired rather than deleted, because a subscription may still point
 * at one; feature flags are deleted outright, and their plan/tenant links
 * cascade away with them.
 */
export async function tidyGlobalRows(): Promise<void> {
  assertTestDatabase(process.env.DATABASE_URL);

  const client = new Client({ connectionString: process.env.DATABASE_URL });
  await client.connect();
  try {
    const plans = await client.query(
      `UPDATE plans SET is_active = false
        WHERE is_active AND (slug ~ '[0-9]{13}' OR name ~ '[0-9]{13}')`
    );
    const flags = await client.query(
      `DELETE FROM feature_flags WHERE key ~ '[0-9]{13}'`
    );

    const retired = plans.rowCount ?? 0;
    const removed = flags.rowCount ?? 0;
    if (retired || removed) {
      console.log(`[tidy] retired ${retired} test plan(s), removed ${removed} test feature flag(s)`);
    }
  } finally {
    await client.end();
  }
}
