import type { Client } from "@/types";

const now = "2026-03-20T10:00:00.000Z";

export const DEMO_CLIENTS: Client[] = [
  {
    id: "demo-client-001",
    name: "Acme Corp",
    email: "contact@acme-demo.example",
    phone: "+213 555 0101",
    address: "123 Rue des Oliviers",
    city: "Alger",
    postal_code: "16000",
    country: "DZ",
    siret: null,
    vat_number: "DZ000000001",
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-client-002",
    name: "Sahara Trading Co.",
    email: "hello@sahara-demo.example",
    phone: "+213 555 0202",
    address: "45 Boulevard de la Liberté",
    city: "Oran",
    postal_code: "31000",
    country: "DZ",
    siret: null,
    vat_number: null,
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-client-003",
    name: "Atlas Industries",
    email: "info@atlas-demo.example",
    phone: "+213 555 0303",
    address: "78 Avenue de l'Indépendance",
    city: "Constantine",
    postal_code: "25000",
    country: "DZ",
    siret: null,
    vat_number: "DZ000000003",
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-client-004",
    name: "Méditerranée Services",
    email: "med-services@demo.example",
    phone: "+213 555 0404",
    address: "12 Rue du Port",
    city: "Béjaïa",
    postal_code: "06000",
    country: "DZ",
    siret: null,
    vat_number: null,
    notes: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-client-005",
    name: "Djurdjura Tech",
    email: "tech@djurdjura-demo.example",
    phone: "+213 555 0505",
    address: "5 Place des Martyrs",
    city: "Tizi Ouzou",
    postal_code: "15000",
    country: "DZ",
    siret: null,
    vat_number: null,
    notes: null,
    created_at: now,
    updated_at: now,
  },
];
