import type { Invoice } from "@/types";
import { DEMO_CLIENTS } from "./clients";
import { DEMO_PRODUCTS } from "./products";

const now = "2026-03-20T10:00:00.000Z";

export const DEMO_INVOICES: Invoice[] = [
  {
    id: "demo-invoice-001",
    invoice_number: "FAC-2026-001",
    client_id: DEMO_CLIENTS[0].id,
    client: DEMO_CLIENTS[0],
    quote_id: null,
    status: "PAID",
    issue_date: "2026-02-15",
    due_date: "2026-03-15",
    subtotal: 150000,
    tax_amount: 28500,
    total: 178500,
    notes: null,
    notes_html: null,
    integrity_hash: null,
    logo_snapshot: null,
    shipping_cost: 0,
    shipping_tax_rate: 0,
    down_payment_percent: 0,
    down_payment_amount: 0,
    is_down_payment_invoice: false,
    parent_quote_id: null,
    lines: [
      {
        id: "demo-invline-001",
        invoice_id: "demo-invoice-001",
        product_id: DEMO_PRODUCTS[0].id,
        product: DEMO_PRODUCTS[0],
        description: "Web Development Package",
        description_html: null,
        quantity: 1,
        unit_price: 150000,
        tax_rate: 19,
        subtotal: 150000,
        tax_amount: 28500,
        total: 178500,
        position: 0,
        group_name: null,
        is_subtotal_line: null,
      },
    ],
    payments: [
      {
        id: "demo-payment-001",
        invoice_id: "demo-invoice-001",
        amount: 178500,
        payment_date: "2026-03-10",
        payment_method: "transfer",
        reference: "VIR-2026-0310",
        notes: null,
        created_at: now,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-invoice-002",
    invoice_number: "FAC-2026-002",
    client_id: DEMO_CLIENTS[1].id,
    client: DEMO_CLIENTS[1],
    quote_id: null,
    status: "ISSUED",
    issue_date: "2026-03-05",
    due_date: "2026-04-05",
    subtotal: 63000,
    tax_amount: 11970,
    total: 74970,
    notes: null,
    notes_html: null,
    integrity_hash: null,
    logo_snapshot: null,
    shipping_cost: 0,
    shipping_tax_rate: 0,
    down_payment_percent: 0,
    down_payment_amount: 0,
    is_down_payment_invoice: false,
    parent_quote_id: null,
    lines: [
      {
        id: "demo-invline-002",
        invoice_id: "demo-invoice-002",
        product_id: DEMO_PRODUCTS[1].id,
        product: DEMO_PRODUCTS[1],
        description: "Logo Design",
        description_html: null,
        quantity: 1,
        unit_price: 35000,
        tax_rate: 19,
        subtotal: 35000,
        tax_amount: 6650,
        total: 41650,
        position: 0,
        group_name: null,
        is_subtotal_line: null,
      },
      {
        id: "demo-invline-003",
        invoice_id: "demo-invoice-002",
        product_id: DEMO_PRODUCTS[2].id,
        product: DEMO_PRODUCTS[2],
        description: "Office Chair - Ergonomic",
        description_html: null,
        quantity: 1,
        unit_price: 28000,
        tax_rate: 19,
        subtotal: 28000,
        tax_amount: 5320,
        total: 33320,
        position: 1,
        group_name: null,
        is_subtotal_line: null,
      },
    ],
    payments: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-invoice-003",
    invoice_number: "FAC-2026-003",
    client_id: DEMO_CLIENTS[2].id,
    client: DEMO_CLIENTS[2],
    quote_id: null,
    status: "DRAFT",
    issue_date: "2026-03-18",
    due_date: "2026-04-18",
    subtotal: 32000,
    tax_amount: 6080,
    total: 38080,
    notes: null,
    notes_html: null,
    integrity_hash: null,
    logo_snapshot: null,
    shipping_cost: 0,
    shipping_tax_rate: 0,
    down_payment_percent: 0,
    down_payment_amount: 0,
    is_down_payment_invoice: false,
    parent_quote_id: null,
    lines: [
      {
        id: "demo-invline-004",
        invoice_id: "demo-invoice-003",
        product_id: DEMO_PRODUCTS[3].id,
        product: DEMO_PRODUCTS[3],
        description: "Consulting - Hourly",
        description_html: null,
        quantity: 4,
        unit_price: 8000,
        tax_rate: 19,
        subtotal: 32000,
        tax_amount: 6080,
        total: 38080,
        position: 0,
        group_name: null,
        is_subtotal_line: null,
      },
    ],
    payments: [],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-invoice-004",
    invoice_number: "FAC-2026-004",
    client_id: DEMO_CLIENTS[3].id,
    client: DEMO_CLIENTS[3],
    quote_id: null,
    status: "PAID",
    issue_date: "2026-02-20",
    due_date: "2026-03-20",
    subtotal: 25000,
    tax_amount: 4750,
    total: 29750,
    notes: null,
    notes_html: null,
    integrity_hash: null,
    logo_snapshot: null,
    shipping_cost: 0,
    shipping_tax_rate: 0,
    down_payment_percent: 0,
    down_payment_amount: 0,
    is_down_payment_invoice: false,
    parent_quote_id: null,
    lines: [
      {
        id: "demo-invline-005",
        invoice_id: "demo-invoice-004",
        product_id: DEMO_PRODUCTS[6].id,
        product: DEMO_PRODUCTS[6],
        description: "Monthly Maintenance",
        description_html: null,
        quantity: 1,
        unit_price: 25000,
        tax_rate: 19,
        subtotal: 25000,
        tax_amount: 4750,
        total: 29750,
        position: 0,
        group_name: null,
        is_subtotal_line: null,
      },
    ],
    payments: [
      {
        id: "demo-payment-002",
        invoice_id: "demo-invoice-004",
        amount: 29750,
        payment_date: "2026-03-18",
        payment_method: "cash",
        reference: null,
        notes: null,
        created_at: now,
      },
    ],
    created_at: now,
    updated_at: now,
  },
];
