import type { Product } from "@/types";

// Services carry a cost as well as a price: the live margin block in the
// quote and invoice forms only appears when a cost is known, and a demo that
// hid it would hide the feature.
const now = "2026-03-20T10:00:00.000Z";

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-product-001",
    designation: "Forfait création de site web",
    description: "Développement complet d'un site vitrine",
    description_html: null,
    unit_price: 150000,
    tax_rate: 19,
    unit: "forfait",
    reference: "WEB-001",
    barcode: null,
    is_service: true,
    category_id: null,
    photo_path: null,
    quantity: null,
    purchase_price: 90000,
    has_variants: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-002",
    designation: "Création de logo",
    description: "Logo professionnel et identité visuelle",
    description_html: null,
    unit_price: 35000,
    tax_rate: 19,
    unit: "piece",
    reference: "DES-001",
    barcode: null,
    is_service: true,
    category_id: null,
    photo_path: null,
    quantity: null,
    purchase_price: 12000,
    has_variants: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-003",
    designation: "Chaise de bureau ergonomique",
    description: "Chaise de bureau réglable",
    description_html: null,
    unit_price: 28500,
    tax_rate: 19,
    unit: "piece",
    reference: "FUR-001",
    barcode: "6000001000013",
    is_service: false,
    category_id: null,
    photo_path: null,
    quantity: 24,
    purchase_price: 18000,
    has_variants: false,
    prices: [
      { id: "demo-price-001", product_id: "demo-product-003", label: "retail", price: 28500, created_at: now, updated_at: now },
      { id: "demo-price-002", product_id: "demo-product-003", label: "wholesale", price: 24000, created_at: now, updated_at: now },
      { id: "demo-price-003", product_id: "demo-product-003", label: "semi_wholesale", price: 26000, created_at: now, updated_at: now },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-004",
    designation: "Conseil à l'heure",
    description: "Conseil aux entreprises, à l'heure",
    description_html: null,
    unit_price: 8000,
    tax_rate: 19,
    unit: "hour",
    reference: "CON-001",
    barcode: null,
    is_service: true,
    category_id: null,
    photo_path: null,
    quantity: null,
    purchase_price: 3500,
    has_variants: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-005",
    designation: "Papier A4 (ramette de 500)",
    description: "Papier A4 haute qualité",
    description_html: null,
    unit_price: 750,
    tax_rate: 9,
    unit: "piece",
    reference: "SUP-001",
    barcode: "6000001000020",
    is_service: false,
    category_id: null,
    photo_path: null,
    quantity: 150,
    purchase_price: 450,
    has_variants: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-006",
    designation: "Support d'ordinateur portable",
    description: "Support portable en aluminium",
    description_html: null,
    unit_price: 4500,
    tax_rate: 19,
    unit: "piece",
    reference: "ACC-001",
    barcode: "6000001000037",
    is_service: false,
    category_id: null,
    photo_path: null,
    quantity: 40,
    purchase_price: 2800,
    has_variants: true,
    variants: [
      { id: "demo-variant-001", product_id: "demo-product-006", name: "Argent", sku: "ACC-001-SLV", barcode: "6000001000044", attributes: { color: "Argent" }, quantity: 25, price_override: null, is_active: true, created_at: now, updated_at: now },
      { id: "demo-variant-002", product_id: "demo-product-006", name: "Noir", sku: "ACC-001-BLK", barcode: "6000001000051", attributes: { color: "Noir" }, quantity: 15, price_override: null, is_active: true, created_at: now, updated_at: now },
      { id: "demo-variant-003", product_id: "demo-product-006", name: "Or rose", sku: "ACC-001-RSG", barcode: null, attributes: { color: "Or rose" }, quantity: 0, price_override: 5000, is_active: true, created_at: now, updated_at: now },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-007",
    designation: "Maintenance mensuelle",
    description: "Contrat de maintenance informatique",
    description_html: null,
    unit_price: 25000,
    tax_rate: 19,
    unit: "month",
    reference: "MNT-001",
    barcode: null,
    is_service: true,
    category_id: null,
    photo_path: null,
    quantity: null,
    purchase_price: 9000,
    has_variants: false,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-008",
    designation: "Hub USB-C 7-en-1",
    description: "Adaptateur multiport USB-C",
    description_html: null,
    unit_price: 3200,
    tax_rate: 19,
    unit: "piece",
    reference: "ACC-002",
    barcode: "6000001000044",
    is_service: false,
    category_id: null,
    photo_path: null,
    quantity: 65,
    purchase_price: 1900,
    has_variants: false,
    created_at: now,
    updated_at: now,
  },
];
