import type { Product } from "@/types";

const now = "2026-03-20T10:00:00.000Z";

export const DEMO_PRODUCTS: Product[] = [
  {
    id: "demo-product-001",
    designation: "Web Development Package",
    description: "Full-stack website development",
    description_html: null,
    unit_price: 150000,
    tax_rate: 19,
    unit: "forfait",
    reference: "WEB-001",
    barcode: null,
    is_service: true,
    category_id: null,
    photo_path: null,
    quantity: null,
    purchase_price: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-002",
    designation: "Logo Design",
    description: "Professional logo and brand identity",
    description_html: null,
    unit_price: 35000,
    tax_rate: 19,
    unit: "piece",
    reference: "DES-001",
    barcode: null,
    is_service: true,
    category_id: null,
    photo_path: null,
    quantity: null,
    purchase_price: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-003",
    designation: "Office Chair - Ergonomic",
    description: "Adjustable ergonomic office chair",
    description_html: null,
    unit_price: 28500,
    tax_rate: 19,
    unit: "piece",
    reference: "FUR-001",
    barcode: "6000001000013",
    is_service: false,
    category_id: null,
    photo_path: null,
    quantity: 24,
    purchase_price: 18000,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-004",
    designation: "Consulting - Hourly",
    description: "Business consulting per hour",
    description_html: null,
    unit_price: 8000,
    tax_rate: 19,
    unit: "hour",
    reference: "CON-001",
    barcode: null,
    is_service: true,
    category_id: null,
    photo_path: null,
    quantity: null,
    purchase_price: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-005",
    designation: "Printer Paper A4 (500 sheets)",
    description: "High-quality A4 paper",
    description_html: null,
    unit_price: 750,
    tax_rate: 9,
    unit: "piece",
    reference: "SUP-001",
    barcode: "6000001000020",
    is_service: false,
    category_id: null,
    photo_path: null,
    quantity: 150,
    purchase_price: 450,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-006",
    designation: "Laptop Stand - Aluminum",
    description: "Portable aluminum laptop stand",
    description_html: null,
    unit_price: 4500,
    tax_rate: 19,
    unit: "piece",
    reference: "ACC-001",
    barcode: "6000001000037",
    is_service: false,
    category_id: null,
    photo_path: null,
    quantity: 40,
    purchase_price: 2800,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-007",
    designation: "Monthly Maintenance",
    description: "Monthly IT maintenance contract",
    description_html: null,
    unit_price: 25000,
    tax_rate: 19,
    unit: "month",
    reference: "MNT-001",
    barcode: null,
    is_service: true,
    category_id: null,
    photo_path: null,
    quantity: null,
    purchase_price: null,
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-product-008",
    designation: "USB-C Hub 7-in-1",
    description: "Multi-port USB-C adapter",
    description_html: null,
    unit_price: 3200,
    tax_rate: 19,
    unit: "piece",
    reference: "ACC-002",
    barcode: "6000001000044",
    is_service: false,
    category_id: null,
    photo_path: null,
    quantity: 65,
    purchase_price: 1900,
    created_at: now,
    updated_at: now,
  },
];
