import type { PurchaseOrder } from "@/types";

const now = "2026-03-20T10:00:00.000Z";

export const DEMO_PURCHASES: PurchaseOrder[] = [
  {
    id: "demo-purchase-001",
    order_number: "PO-20260315-0001",
    supplier_id: "demo-supplier-001",
    supplier: {
      id: "demo-supplier-001",
      name: "TechnoPlus Distribution",
      email: "orders@technoplus-demo.example",
      phone: "+213 555 9001",
      address: "Zone Industrielle, Lot 12, Rouiba",
      notes: null,
      created_at: now,
      updated_at: now,
    },
    status: "CONFIRMED",
    order_date: "2026-03-15",
    confirmed_date: "2026-03-17",
    paid_from_register: true,
    register_id: null,
    session_id: null,
    payment_status: "PAID",
    subtotal: 45000,
    tax_amount: 8550,
    total: 53550,
    notes: null,
    lines: [
      {
        id: "demo-pol-001",
        order_id: "demo-purchase-001",
        product_id: "demo-product-003",
        variant_id: null,
        quantity: 10,
        unit_price: 2800,
        previous_price: 2500,
        use_average_price: true,
        subtotal: 28000,
        tax_rate: 19,
        tax_amount: 5320,
        total: 33320,
      },
      {
        id: "demo-pol-002",
        order_id: "demo-purchase-001",
        product_id: "demo-product-005",
        variant_id: null,
        quantity: 20,
        unit_price: 850,
        previous_price: 850,
        use_average_price: false,
        subtotal: 17000,
        tax_rate: 19,
        tax_amount: 3230,
        total: 20230,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-purchase-002",
    order_number: "PO-20260318-0001",
    supplier_id: "demo-supplier-002",
    supplier: {
      id: "demo-supplier-002",
      name: "Papeterie du Maghreb",
      email: "contact@papeterie-demo.example",
      phone: "+213 555 9002",
      address: "22 Rue Didouche Mourad, Alger",
      notes: null,
      created_at: now,
      updated_at: now,
    },
    status: "PENDING",
    order_date: "2026-03-18",
    confirmed_date: null,
    paid_from_register: false,
    register_id: null,
    session_id: null,
    payment_status: "UNPAID",
    subtotal: 12000,
    tax_amount: 2280,
    total: 14280,
    notes: "Waiting for delivery",
    lines: [
      {
        id: "demo-pol-003",
        order_id: "demo-purchase-002",
        product_id: "demo-product-006",
        variant_id: null,
        quantity: 15,
        unit_price: 800,
        previous_price: null,
        use_average_price: false,
        subtotal: 12000,
        tax_rate: 19,
        tax_amount: 2280,
        total: 14280,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-purchase-003",
    order_number: "PO-20260320-0001",
    supplier_id: "demo-supplier-003",
    supplier: {
      id: "demo-supplier-003",
      name: "MobilierPro Algérie",
      email: "ventes@mobilierpro-demo.example",
      phone: "+213 555 9003",
      address: "Route Nationale 5, Blida",
      notes: null,
      created_at: now,
      updated_at: now,
    },
    status: "CONFIRMED",
    order_date: "2026-03-20",
    confirmed_date: "2026-03-20",
    paid_from_register: false,
    register_id: null,
    session_id: null,
    payment_status: "UNPAID",
    subtotal: 85000,
    tax_amount: 16150,
    total: 101150,
    notes: "Supplier credit - payment due in 30 days",
    lines: [
      {
        id: "demo-pol-004",
        order_id: "demo-purchase-003",
        product_id: "demo-product-008",
        variant_id: null,
        quantity: 5,
        unit_price: 17000,
        previous_price: 18000,
        use_average_price: true,
        subtotal: 85000,
        tax_rate: 19,
        tax_amount: 16150,
        total: 101150,
      },
    ],
    created_at: now,
    updated_at: now,
  },
];
