import type { Quote } from "@/types";
import { DEMO_CLIENTS } from "./clients";
import { DEMO_PRODUCTS } from "./products";

const now = "2026-03-20T10:00:00.000Z";

export const DEMO_QUOTES: Quote[] = [
  {
    id: "demo-quote-001",
    quote_number: "DEV-2026-001",
    client_id: DEMO_CLIENTS[4].id,
    client: DEMO_CLIENTS[4],
    status: "SENT",
    issue_date: "2026-03-12",
    validity_date: "2026-04-12",
    subtotal: 185000,
    tax_amount: 35150,
    total: 220150,
    notes: null,
    notes_html: null,
    logo_snapshot: null,
    shipping_cost: 0,
    shipping_tax_rate: 0,
    down_payment_percent: 30,
    down_payment_amount: 66045,
    lines: [
      {
        id: "demo-qtline-001",
        quote_id: "demo-quote-001",
        product_id: DEMO_PRODUCTS[0].id,
        product: DEMO_PRODUCTS[0],
        description: "Web Development Package",
        description_html: null,
        quantity: 1,
        unit_price: 150000,
        tax_rate: 19,
        subtotal: 150000,
        tax_amount: 28500,
        total: 178500,
        position: 0,
        group_name: null,
        is_subtotal_line: null,
      },
      {
        id: "demo-qtline-002",
        quote_id: "demo-quote-001",
        product_id: DEMO_PRODUCTS[1].id,
        product: DEMO_PRODUCTS[1],
        description: "Logo Design",
        description_html: null,
        quantity: 1,
        unit_price: 35000,
        tax_rate: 19,
        subtotal: 35000,
        tax_amount: 6650,
        total: 41650,
        position: 1,
        group_name: null,
        is_subtotal_line: null,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-quote-002",
    quote_number: "DEV-2026-002",
    client_id: DEMO_CLIENTS[0].id,
    client: DEMO_CLIENTS[0],
    status: "ACCEPTED",
    issue_date: "2026-02-28",
    validity_date: "2026-03-28",
    subtotal: 50000,
    tax_amount: 9500,
    total: 59500,
    notes: null,
    notes_html: null,
    logo_snapshot: null,
    shipping_cost: 0,
    shipping_tax_rate: 0,
    down_payment_percent: 0,
    down_payment_amount: 0,
    lines: [
      {
        id: "demo-qtline-003",
        quote_id: "demo-quote-002",
        product_id: DEMO_PRODUCTS[6].id,
        product: DEMO_PRODUCTS[6],
        description: "Monthly Maintenance",
        description_html: null,
        quantity: 2,
        unit_price: 25000,
        tax_rate: 19,
        subtotal: 50000,
        tax_amount: 9500,
        total: 59500,
        position: 0,
        group_name: null,
        is_subtotal_line: null,
      },
    ],
    created_at: now,
    updated_at: now,
  },
  {
    id: "demo-quote-003",
    quote_number: "DEV-2026-003",
    client_id: DEMO_CLIENTS[2].id,
    client: DEMO_CLIENTS[2],
    status: "DRAFT",
    issue_date: "2026-03-19",
    validity_date: "2026-04-19",
    subtotal: 56500,
    tax_amount: 10735,
    total: 67235,
    notes: null,
    notes_html: null,
    logo_snapshot: null,
    shipping_cost: 0,
    shipping_tax_rate: 0,
    down_payment_percent: 0,
    down_payment_amount: 0,
    lines: [
      {
        id: "demo-qtline-004",
        quote_id: "demo-quote-003",
        product_id: DEMO_PRODUCTS[2].id,
        product: DEMO_PRODUCTS[2],
        description: "Office Chair - Ergonomic",
        description_html: null,
        quantity: 2,
        unit_price: 28500,
        tax_rate: 19,
        subtotal: 57000,
        tax_amount: 10830,
        total: 67830,
        position: 0,
        group_name: null,
        is_subtotal_line: null,
      },
    ],
    created_at: now,
    updated_at: now,
  },
];
